### ISSUE TITLE
Enum constant SMC_MSG_DisableHotPlug appears incorrect

### ISSUE THREAD

**Issue by obilaniu** [openSIL/openSIL#3]
At [this](https://github.com/openSIL/openSIL/blob/d7e33b8306b89151d72fcb4532d5d75256f6a3e5/xUSL/SMU/SmuDefs.h#LL49C1-L49C54) line of code, it appears that a mistake has been made in the value of the `enum` constant `SMC_MSG_DisableHotPlug`:

```c
  SMC_MSG_EnableHotplug                       = 0x18,
  SMC_MSG_DisableHotPlug                      = 0xFF,
  SMC_MSG_SetI2CBusSwitchBaseAddress          = 0x1A,
```

The surrounding context invites the inference that it ought to have been `0x19`.

**Comment by pbgrimes** [comment]
Thanks for reporting this.  The 0xFF is actually intentional (but unclear).
Support for DisableHotPlug via SMC message is not implemented. 0xFF is passed to indicate an invalid/unsupported message has been sent.

I'll update the code to remove the "magic number".
